### ISSUE TITLE
Webpack Compilation Error

### ISSUE THREAD

**Issue by TahirMehmood8082** [shakacode/cypress-on-rails#146]
**by cypress when integrate with rails application with gem "cypress-on-rails"**
**When cypress test run on terminal: "cypress open" generates "Webpack Compilation Error"**
Error: Webpack Compilation Error
Module not found: Error: Can't resolve 'cypress-factory' in '/path/spec/cypress/support'
    at Watching.handle [as handler] (/home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/@packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:212:23)
    at /home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/webpack/lib/Watching.js:303:9
    at Hook.eval [as callAsync] (eval at create (/home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/tapable/lib/Hook.js:18:14)
    at Watching._done (/home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/webpack/lib/Watching.js:299:28)
    at /home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/webpack/lib/Watching.js:213:21
    at Compiler.emitRecords (/home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:919:5)
    at /home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/webpack/lib/Watching.js:191:22
    at /home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:885:14
    at Hook.eval [as callAsync] (eval at create (/home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/tapable/lib/Hook.js:18:14)
    at /home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:882:27
    at /home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/neo-async/async.js:2818:7
    at done (/home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/neo-async/async.js:3522:9)
    at Hook.eval [as callAsync] (eval at create (/home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/tapable/lib/Hook.js:18:14)
    at /home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/webpack/lib/Compiler.js:736:33
    at /home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/graceful-fs/graceful-fs.js:143:16
    at /home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /home/.cache/Cypress/13.5.1/Cypress/resources/app/node_modules/@packages/server/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:200:23)

When i tried to add package, normally webpack compilation error caused when package is missing or import hierarchy issue, 
**yarn add cypress-factory**
yarn add v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/cypress-factory: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/path/Rails/my-project-name/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
=======================================================================
**i know wrong import cause webpack issue, but in my scenario there is not any wrong import**

**Comment by justin808** [comment]
Typo?

![image](https://github.com/shakacode/cypress-on-rails/assets/1118459/46e1a39b-24e7-4f93-a682-34e1498368b8)

**Comment by TahirMehmood8082** [comment]
but point is, i have use factory-bot gem of ruby on rails and i watched this npm package
01-there is nothing **cypress-factory** written in my code or files i double check this, from where it is orignating?

**Comment by justin808** [comment]
Closing as stale: this is a Cypress webpack-preprocessor resolution error in the app's own `spec/cypress/support` setup rather than something this gem controls, and there's been no reproduction for over two years. If you still hit it on a current version, please open a new issue with your `cypress.config.js` and support file.
