### ISSUE TITLE
Getting error 500 when visiting root (/) on CI but works perfectly in local

### ISSUE THREAD

**Issue by markhermano** [shakacode/cypress-on-rails#151]
Hello,

I tried to make this work last week and I was successful in having green tests in local but when I tried to this up in GitHub actions  I was getting error 500 when visiting the root directory after loading the scenarios.

![image](https://github.com/shakacode/cypress-on-rails/assets/16017297/d17355ae-57bb-4ea8-9f61-0afeadab94d6)
![image](https://github.com/shakacode/cypress-on-rails/assets/16017297/fb3f28a4-7498-470f-bcec-530a6a34e1af)

Here is my setup
```ruby
#e2e_helper.rb

require "factory_bot_rails"
require "cypress_on_rails/smart_factory_wrapper"

# I added this because our factoryBot have a custom strategy called cache
class CustomCypressOnRails < CypressOnRails::SmartFactoryWrapper
  def self.cache(*args) end
  def cache(*args) end
end

factory = FactoryBot

CustomCypressOnRails.configure(
  always_reload: false,
  factory: factory,
  files: [
    Rails.root.join("spec", "factories", "*.rb"),
    Rails.root.join("spec", "factories", "**", "*.rb")
  ]
)

```

```ruby
# scenarios/common.rb
currency = FactoryBot.create(:currency)
user_group = FactoryBot.create(:user_group)
market_feed = FactoryBot.create(:market_feed_nz, currency: currency)
user = FactoryBot.create(:quentin, user_group: user_group)
supplier_group = FactoryBot.create(:supplier_group_nz)
community = FactoryBot.create(:community1)
product_type = FactoryBot.create(:product_type)
site = FactoryBot.create(:site, user_group: user_group, site_market_feed: market_feed, business: user,
                                supplier_group: supplier_group, community: community, default_currency: currency,
                                default_product_type: product_type)

FactoryBot.create(:site_domain2, site: site)
```

```ts
// vueBackofficeLayout.spec.cy.ts
describe('Vue Backoffice Layout', () => {
  before(() => {
    cy.appScenario('common')
    cy.login({ username: 'quentin', password: 'secret' })
  })

  beforeEach(() => {
    cy.visit('/profile/index?vue=3')
  })

  it('renders vue backoffice components', () => {
    cy.get('div.navbar').within(() => {
      cy.get('svg.is-active.hamburger')
      cy.get('div.el-select.select-vue')
      cy.get('div.el-dropdown').contains('Quentin Quet')
      cy.get('span.el-avatar')
    })
    cy.get('div.has-logo.sidebar-container').within(() => {
      cy.contains('Local Retail Host')
      cy.get('ul[role="menubar"]')
    })
    cy.get('div.main-container')
  })
})

```

I'm guessing Cypress was not able to load the scenarios but it should at least return a 404 instead of 500.
Can you guys point me to what I miss here? It's kinda tricky if it can't be replicated locally.

**Comment by grantspeelman** [comment]
Looks like `cy.login({ username: 'quentin', password: 'secret' })` is failing

**Comment by markhermano** [comment]
> Looks like `cy.login({ username: 'quentin', password: 'secret' })` is failing

Yes, but it fails right on the first line which is the visit to the root.

```ts
// spec-cypress/support/commands.ts
Cypress.Commands.add('login', (user: UserCredentials) => {
  const { username, password } = user
  cy.session([username],
    () => {
      cy.visit('/')
      cy.get('nav.navbar.hidden-xs a').contains('Login/Sign up').click()
      cy.get('#main-content').find('#user_name').type(username)
      cy.get('#main-content').find('#password').type(password)
      cy.get('#main-content').contains('Login and Checkout').click()
      cy.get('p#flash_success').contains('You are logged in as Local Retail Host')
    },
    {
      validate() {
        cy.request('/api/v1/current_user', {
          method: 'GET'
        }).its('status').should('equal', 200)
      }
    }
  )
})

**Comment by grantspeelman** [comment]
maybe if you store the log folder as an artifact you can look at the logs and see why it's giving a 500 error.

**Comment by markhermano** [comment]
> maybe if you store the log folder as an artifact you can look at the logs and see why it's giving a 500 error.

@grantspeelman Sorry for the late update but thanks for the tip. I added the logs in the artifacts and I was able to see the problem which is when the Database Cleaner is triggered Paper Trail is querying versions table which does not exist. 
But paper trail is disabled in the initializers and this only happens in CI.

```bash
Started POST "/__e2e__/command" for 127.0.0.1 at 2024-01-16 05:54:39 +0000
[CY_DEV] handle_command: {"name"=>"log_fail", "options"=>{"error_message"=>"`cy.visit()` failed trying to load:\n\nhttp://localhost:5173/\n\nThe response we received from your web server was:\n\n  > 500: Internal Server Error\n\nThis was considered a failure because the status code was not `2xx`.\n\nIf you do not want status codes to cause failures pass the option: `failOnStatusCode: false`\n\nThis error occurred while creating the session. Because the session setup failed, we failed the test.", "runnable_full_title"=>"Bin Settings \"before each\" hook"}}
[CY_DEV]   [1m[36mActiveRecord::SessionStore::Session Load (5.1ms)[0m  [1m[34mSELECT `sessions`.* FROM `sessions` LIMIT 100[0m
[CY_DEV]   [1m[36mPaperTrail::Version Load (1.6ms)[0m  [1m[34mSELECT `versions`.* FROM `versions` LIMIT 100[0m
[CY_DEV] fail to execute /app/spec-cypress/e2e/app_commands/log_fail.rb: Mysql2::Error: Table 'app_test.versions' doesn't exist
[CY_DEV] /app/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
/app/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
/app/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
/app/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
```

Anyway, this is not a problem with cypress-on-rails gem but if you guys have some tips or ideas to solve my issue, I would appreciate it. Thank you very much.

**Comment by grantspeelman** [comment]
worth checking if it's disable also for the test environment, because maybe on your local you running cypress against your development environment and on CI you run against the test environment.
Hope that helps.
