### ISSUE TITLE
Seems to generate a cypress directory in the main folder

### ISSUE THREAD

**Issue by jeznag** [shakacode/cypress-on-rails#2]
![cypress](https://user-images.githubusercontent.com/1034890/33357661-99bf9b26-d517-11e7-9b03-6cfdc084046a.gif)
I run `bundle exec cypress` and it seems to ignore the spec/cypress dir and creates a new one in root dir. The cypress UI dialog uses the tests in the new dir and ignores the ones I have in spec/cypress.

**Comment by spielhoelle** [comment]
For me the same. /cypress folder gets created when I run the cypress ui.
In addition to this none of the tests are working properly after the initial installation.
My Tests fail with that error in the cypress UI
```
CypressError: cy.request() failed on:

http://localhost:51257/__cypress__/scenario

The response we received from your web server was:

  > 500: Server Error

This was considered a failure because the status code was not '2xx' or '3xx'.

If you do not want status codes to cause failures pass the option: 'failOnStatusCode: false'

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://localhost:51257/__cypress__/scenario
Headers: {
  "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/1.1.4 Chrome/53.0.2785.143 Electron/1.4.6 Safari/537.36",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate",
  "content-length": 20
}
Body: {"scenario":"basic"}

-----------------------------------------------------------

The response we got was:

Status: 500 - Server Error
Headers: {
  "connection": "close",
  "content-length": "77"
}
Body: An unhandled lowlevel error occurred. The application logs may have details.
```

And that logs the cypress log in the console.
```2017-12-10 12:12:59 +0100: Rack app error handling request { POST /__cypress__/scenario }
#<NoMethodError: private method `load' called for nil:NilClass>
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/cypress-on-rails-0.2.1/lib/cypress/middleware.rb:58:in `handle_scenario'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/cypress-on-rails-0.2.1/lib/cypress/middleware.rb:14:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/conditional_get.rb:38:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:97:in `run_callbacks'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/railties-5.1.4/lib/rails/rack/logger.rb:36:in `call_app'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/railties-5.1.4/lib/rails/rack/logger.rb:24:in `block in call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:69:in `tagged'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/railties-5.1.4/lib/rails/rack/logger.rb:24:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/activesupport-5.1.4/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/static.rb:125:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/railties-5.1.4/lib/rails/engine.rb:522:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/capybara-2.15.4/lib/capybara/server.rb:44:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'```

**Comment by grantspeelman** [comment]
Hey @jeznag, thanks for the feedback.

I removed the ruby cypress executable since version 1.0, so not sure how `bundle exec cypress` is working unless you are running an earlier version. 

Try `bundle update cypress-on-rails` and check the [Usage](https://github.com/shakacode/cypress-on-rails#usage) in the README.md:
```bash
yarn cypress open --project ./spec
```

We looking into reintroducing a ruby executable to wrap cypress, similar to how rails does for webpack but for now see if the above steps helps

**Comment by grantspeelman** [comment]
Whoops, only noticed now that this is from Nov 2017 and not Nov 2018.
Closing this.

**Comment by noccor** [comment]
Hey - I'm actually having this issue. I have two projects using cypress-on-rails... the project I first used this from runs flawlessly... the project I've just added this to.. keeps creating a new spec folder in my Users directory and loading cypress tests from there (unless I provide a full path to the projects spec folder) 

Using:
cypress-on-rails 1.5.0
Ruby 2.6.5
Rails 6.0.1

At this point have followed the guide, ran the generators, then booted up cypress.

**Comment by grantspeelman** [comment]
hmmmm, not sure what it could be, can you provide some output when running 
`bin/rails g cypress_on_rails:install`

**Comment by noccor** [comment]
Sure:

```Running via Spring preloader in process 32170
/Users/connor/.rvm/gems/ruby-2.6.5/gems/spring-2.1.0/lib/spring/application.rb:199: warning: Insecure world writable dir /Users in PATH, mode 040777
   identical  config/initializers/cypress_on_rails.rb
    conflict  spec/cypress/cypress_helper.rb
Overwrite /Users/connor/Documents/apps/startersite/spec/cypress/cypress_helper.rb? (enter "h" for help) [Ynaqdhm] n
        skip  spec/cypress/cypress_helper.rb
    conflict  spec/cypress/support/on-rails.js
Overwrite /Users/connor/Documents/apps/startersite/spec/cypress/support/on-rails.js? (enter "h" for help) [Ynaqdhm] n
        skip  spec/cypress/support/on-rails.js
       exist  spec/cypress/app_commands
   identical  spec/cypress/app_commands/activerecord_fixtures.rb
   identical  spec/cypress/app_commands/clean.rb
   identical  spec/cypress/app_commands/eval.rb
   identical  spec/cypress/app_commands/factory_bot.rb
   identical  spec/cypress/app_commands/log_fail.rb
    conflict  spec/cypress/app_commands/scenarios/basic.rb
Overwrite /Users/connor/Documents/apps/startersite/spec/cypress/app_commands/scenarios/basic.rb? (enter "h" for help) [Ynaqdhm] n
        skip  spec/cypress/app_commands/scenarios/basic.rb
      create  spec/cypress/integration/rails_examples
      create  spec/cypress/integration/rails_examples/advance_factory_bot_spec.js
      create  spec/cypress/integration/rails_examples/other_spec.js
      create  spec/cypress/integration/rails_examples/using_factory_bot_spec.js
      create  spec/cypress/integration/rails_examples/using_fixtures_spec.js
      create  spec/cypress/integration/rails_examples/using_scenarios_spec.js
      insert  spec/cypress/support/index.js
        gsub  config/environments/test.rb```

**Comment by grantspeelman** [comment]
@noccor i don't see anything wrong, the default directory for cypress is `spec/cypress`
You can change the default directory like this

```
bin/rails g cypress_on_rails:install --cypress_folder=cypress
```
