### ISSUE TITLE
Tests failing after initial installation and configuration

### ISSUE THREAD

**Issue by spielhoelle** [shakacode/cypress-on-rails#3]
Issue #2 also happens in my project, which maybe causes also my error
`. /cypress` folder gets created when I run the cypress ui. Usually it should take the files in ./spec/cypress

In addition to this none of the tests are working properly after the initial installation.
I tried to compare it with the example project - not successful. 

my Tests fail with that error in the cypress UI
```
CypressError: cy.request() failed on:

http://localhost:51257/__cypress__/scenario

The response we received from your web server was:

  > 500: Server Error

This was considered a failure because the status code was not '2xx' or '3xx'.

If you do not want status codes to cause failures pass the option: 'failOnStatusCode: false'

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://localhost:51257/__cypress__/scenario
Headers: {
  "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_1) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/1.1.4 Chrome/53.0.2785.143 Electron/1.4.6 Safari/537.36",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate",
  "content-length": 20
}
Body: {"scenario":"basic"}

-----------------------------------------------------------

The response we got was:

Status: 500 - Server Error
Headers: {
  "connection": "close",
  "content-length": "77"
}
Body: An unhandled lowlevel error occurred. The application logs may have details.
```

And that logs the cypress log in the console.
```2017-12-10 12:12:59 +0100: Rack app error handling request { POST /__cypress__/scenario }
#<NoMethodError: private method `load' called for nil:NilClass>
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/cypress-on-rails-0.2.1/lib/cypress/middleware.rb:58:in `handle_scenario'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/cypress-on-rails-0.2.1/lib/cypress/middleware.rb:14:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/conditional_get.rb:38:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/activesupport-5.1.4/lib/active_support/callbacks.rb:97:in `run_callbacks'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/railties-5.1.4/lib/rails/rack/logger.rb:36:in `call_app'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/railties-5.1.4/lib/rails/rack/logger.rb:24:in `block in call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:26:in `tagged'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:69:in `tagged'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/railties-5.1.4/lib/rails/rack/logger.rb:24:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/activesupport-5.1.4/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/actionpack-5.1.4/lib/action_dispatch/middleware/static.rb:125:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/railties-5.1.4/lib/rails/engine.rb:522:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/urlmap.rb:68:in `block in call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `each'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/rack-2.0.3/lib/rack/urlmap.rb:53:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/capybara-2.15.4/lib/capybara/server.rb:44:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `call'
/Users/thomaskuhnert/.rvm/gems/ruby-2.2.5/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'```

**Comment by derfred** [comment]
Sorry for the slow response. I have now released a new version, do you want to try again?

I personally have switched to using the ```cy.rails``` approach, as I found it more natural to having the entire test, including setup in one file.

Are you using the scenarios?

**Comment by spielhoelle** [comment]
I tried it now in my application where I want to switch from cypress.js to your gem version. But now another error occurs:

```
$ bundle exec cypress
Puma starting in single mode...
* Version 3.10.0 (ruby 2.2.5-p319), codename: Russell's Teapot
* Min threads: 0, max threads: 4
* Environment: test
* Listening on tcp://127.0.0.1:65025
Use Ctrl-C to stop
CYPRESS: yarn run v1.1.0
CYPRESS: $ "/Users/tommy/develop/project/node_modules/.bin/cypress" "open" "--env" "SERVER_PORT=65025" "--record" "--key" "1511081a-e957-44f8-8df7-f305da53a39f" "-c" "videosFolder=spec/cypress/videos,fixturesFolder=spec/cypress/fixtures,integrationFolder=spec/cypress/integrations/,supportFile=spec/cypress/support/setup.js"

  error: unknown option `--record'

error Command failed with exit code 1.
CYPRESS: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


$ bundle exec cypress run
Puma starting in single mode...
* Version 3.10.0 (ruby 2.2.5-p319), codename: Russell's Teapot
* Min threads: 0, max threads: 4
* Environment: test
* Listening on tcp://127.0.0.1:65064
Use Ctrl-C to stop
CYPRESS: yarn run v1.1.0
CYPRESS: $ "/Users/tommy/develop/project/node_modules/.bin/cypress" "run" "--env" "SERVER_PORT=65064" "--record" "--key" "1511081a-e957-44f8-8df7-f305da53a39f" "-c" "videosFolder=spec/cypress/videos,fixturesFolder=spec/cypress/fixtures,integrationFolder=spec/cypress/integrations/,supportFile=spec/cypress/support/setup.js"
CYPRESS: You passed the --record flag but this project has not been setup to record.
CYPRESS:
CYPRESS: This project is missing the 'projectId' inside of 'cypress.json'.
CYPRESS:
CYPRESS: We cannot uniquely identify this project without this id.
CYPRESS:
CYPRESS: You need to setup this project to record. This will generate a unique 'projectId'.
CYPRESS:
CYPRESS: Alternatively if you omit the --record flag this project will run without recording.
CYPRESS:
CYPRESS: https://on.cypress.io/recording-project-runs
error Command failed with exit code 1.
CYPRESS: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

When I try the gem in a new sample rails app its like that:

```
Puma starting in single mode...
* Version 3.11.2 (ruby 2.2.5-p319), codename: Love Song
* Min threads: 0, max threads: 4
* Environment: test
* Listening on tcp://127.0.0.1:50936
Use Ctrl-C to stop
/Users/tommy/.rvm/gems/ruby-2.2.5/gems/cypress-on-rails-0.2.2/lib/cypress/runner.rb:11:in `run': uninitialized constant Cypress::Runner::Open3 (NameError)
	from /Users/tommy/.rvm/gems/ruby-2.2.5/gems/cypress-on-rails-0.2.2/bin/cypress:3:in `<top (required)>'
	from /Users/tommy/.rvm/gems/ruby-2.2.5/bin/cypress:22:in `load'
	from /Users/tommy/.rvm/gems/ruby-2.2.5/bin/cypress:22:in `<main>'
	from /Users/tommy/.rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `eval'
	from /Users/tommy/.rvm/gems/ruby-2.2.5/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by wjessop** [comment]
@spielhoelle Did you ever solve this? I am having the same issue.

**Comment by spielhoelle** [comment]
No just started using vendor/npm cypress
