### ISSUE TITLE
Error after clicking on a link

### ISSUE THREAD

**Issue by clivialee** [shakacode/cypress-on-rails#30]
The link looks like this
```
<a class="btn btn--success tooltip" data-content="Moves the resolution to step 2 of the process." data-variation="tiny" rel="nofollow" data-method="put" href="/resolutions/1/update_status?resolution%5Bstatus%5D=filed">
    <i class="fas fa-folder-open"></i> File
</a>
```

The error in the browser goes
```
Uncaught TypeError: Illegal invocation

This error originated from your application code, not from Cypress.

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the 'uncaught:exception' event.

https://on.cypress.io/uncaught-exception-from-application
    at Rails.matches (http://localhost:5002/assets/application-c9b4193f20d5f0f68dc035d3223a1796052947e62aee4c4980d29afb8382e94f.js:59:20)
    at HTMLAnchorElement.Rails.disableElement (http://localhost:5002/assets/application-c9b4193f20d5f0f68dc035d3223a1796052947e62aee4c4980d29afb8382e94f.js:419:13)
    at HTMLDocument.<anonymous> (http://localhost:5002/assets/application-c9b4193f20d5f0f68dc035d3223a1796052947e62aee4c4980d29afb8382e94f.js:174:52)
From previous event:
    at run (http://localhost:5002/__cypress/runner/cypress_runner.js:80153:15)
    at Object.cy.<computed> [as visit] (http://localhost:5002/__cypress/runner/cypress_runner.js:80380:11)
    at Context.runnable.fn (http://localhost:5002/__cypress/runner/cypress_runner.js:80518:20)
    at callFn (http://localhost:5002/__cypress/runner/cypress_runner.js:52609:21)
    at Test.Runnable.run (http://localhost:5002/__cypress/runner/cypress_runner.js:52602:7)
    at http://localhost:5002/__cypress/runner/cypress_runner.js:83512:28
From previous event:
    at Object.onRunnableRun (http://localhost:5002/__cypress/runner/cypress_runner.js:83507:20)
    at $Cypress.action (http://localhost:5002/__cypress/runner/cypress_runner.js:78777:51)
    at Test.Runnable.run (http://localhost:5002/__cypress/runner/cypress_runner.js:82573:20)
    at Runner.runTest (http://localhost:5002/__cypress/runner/cypress_runner.js:53072:10)
    at http://localhost:5002/__cypress/runner/cypress_runner.js:53178:12
    at next (http://localhost:5002/__cypress/runner/cypress_runner.js:52992:14)
    at http://localhost:5002/__cypress/runner/cypress_runner.js:53002:7
    at next (http://localhost:5002/__cypress/runner/cypress_runner.js:52934:14)
    at http://localhost:5002/__cypress/runner/cypress_runner.js:52965:7
    at next (http://localhost:5002/__cypress/runner/cypress_runner.js:83477:16)
    at http://localhost:5002/__cypress/runner/cypress_runner.js:83489:11
From previous event:
    at onNext (http://localhost:5002/__cypress/runner/cypress_runner.js:83488:57)
    at done (http://localhost:5002/__cypress/runner/cypress_runner.js:52570:5)
    at http://localhost:5002/__cypress/runner/cypress_runner.js:52614:11
From previous event:
    at callFn (http://localhost:5002/__cypress/runner/cypress_runner.js:52613:10)
    at Hook.Runnable.run (http://localhost:5002/__cypress/runner/cypress_runner.js:52602:7)
    at http://localhost:5002/__cypress/runner/cypress_runner.js:83512:28
From previous event:
    at Object.onRunnableRun (http://localhost:5002/__cypress/runner/cypress_runner.js:83507:20)
    at $Cypress.action (http://localhost:5002/__cypress/runner/cypress_runner.js:78777:51)
    at Hook.Runnable.run (http://localhost:5002/__cypress/runner/cypress_runner.js:82573:20)
    at next (http://localhost:5002/__cypress/runner/cypress_runner.js:52948:10)
    at http://localhost:5002/__cypress/runner/cypress_runner.js:52970:5
    at timeslice (http://localhost:5002/__cypress/runner/cypress_runner.js:48211:27)
```

The rails error log in the terminal goes
```
2019-07-18 18:49:52 +0800: Rack app error handling request { POST /__cypress__/command }
#<ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect table name '': SELECT  ``.* FROM `` LIMIT 100>
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cypress-on-rails-1.4.0/lib/cypress_on_rails/command_executor.rb:9:in `eval'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:131:in `block in query'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `handle_interrupt'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mysql2-0.5.2/lib/mysql2/client.rb:130:in `query'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:187:in `block (2 levels) in execute'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:48:in `block in permit_concurrent_loads'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/dependencies/interlock.rb:47:in `permit_concurrent_loads'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:186:in `block in execute'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:581:in `block (2 levels) in log'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:580:in `block in log'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:571:in `log'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:185:in `execute'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/mysql/database_statements.rb:28:in `execute'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:196:in `execute_and_free'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/mysql/database_statements.rb:33:in `exec_query'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:478:in `select'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/database_statements.rb:70:in `select_all'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:104:in `block in select_all'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:127:in `block in cache_sql'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:113:in `cache_sql'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/abstract/query_cache.rb:104:in `select_all'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/connection_adapters/mysql/database_statements.rb:12:in `select_all'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/querying.rb:41:in `find_by_sql'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation.rb:560:in `block in exec_queries'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation.rb:584:in `skip_query_cache_if_necessary'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation.rb:547:in `exec_queries'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation.rb:422:in `load'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation.rb:200:in `records'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activerecord-5.2.3/lib/active_record/relation/delegation.rb:71:in `each'
(eval):14:in `map'
(eval):14:in `block in load'
(eval):13:in `each'
(eval):13:in `each_with_object'
(eval):13:in `load'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cypress-on-rails-1.4.0/lib/cypress_on_rails/command_executor.rb:9:in `eval'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cypress-on-rails-1.4.0/lib/cypress_on_rails/command_executor.rb:9:in `load'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cypress-on-rails-1.4.0/lib/cypress_on_rails/middleware.rb:58:in `block in handle_command'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cypress-on-rails-1.4.0/lib/cypress_on_rails/middleware.rb:58:in `each'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cypress-on-rails-1.4.0/lib/cypress_on_rails/middleware.rb:58:in `handle_command'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cypress-on-rails-1.4.0/lib/cypress_on_rails/middleware.rb:18:in `block in call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cypress-on-rails-1.4.0/lib/cypress_on_rails/configuration.rb:23:in `block in tagged_logged'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cypress-on-rails-1.4.0/lib/cypress_on_rails/configuration.rb:23:in `tagged_logged'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/cypress-on-rails-1.4.0/lib/cypress_on_rails/middleware.rb:18:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/tempfile_reaper.rb:15:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:38:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:38:in `call_app'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/static.rb:127:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
/Users/liyuezhi/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

I'm pretty sure the error has nothing to do with the app itself because:
when I click on the same link outside of cypress (in test environment), no error is thrown in either the browser console nor the rails log;
I delete all the code from the corresponding controller action, the error still happens, so the error happens;
I puts a log command at the beginning of the controller action, nothing was logged, which means none of the controller code is even executed.

**Comment by grantspeelman** [comment]
@clivialee it sounds like this is an error happening in the browser. 
Possibly a javascript error or an error in cypress itself.
Are you using the latest version ([currently 3.4.0](https://docs.cypress.io/guides/references/changelog.html#3-4-0)) of Cypress?
