### ISSUE TITLE
Errors creating Factory

### ISSUE THREAD

**Issue by stoplion** [shakacode/cypress-on-rails#59]
- Running Rails in test env √
- Latest cypress-on-rails √

Errors When creating a factory ...

```
const testUserName = '@bossmaster'
    const testUserEmail = 'testuser123@email.com'
    const testTitle = 'Another test title'
    let testUser;

    before(() => {
      cy.app('clean');
      cy.appFactories([
        ['create', 'user', { username: testUserName, email: testUserEmail } ],
      ]).then((data) => {
        testUser = data[0]

        const attrs = {
          user_id: testUser.id,
          title: testTitle
        }

        cy.appFactories(['create', 'post', attrs])
        cy.forceLogin({ email: testUserEmail });
      })
```

Stack Trace:

```
Because this error occurred during a before all hook we are skipping the remaining tests in the current suite: As a logged in userLearn more
View stack trace
CypressError: `cy.request()` failed on:

http://localhost:5000/__cypress__/command

The response we received from your web server was:

  > 500: Server Error

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: POST
URL: http://localhost:5000/__cypress__/command
Headers: {
  "Connection": "keep-alive",
  "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/4.4.0 Chrome/80.0.3987.158 Electron/8.2.0 Safari/537.36",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate",
  "content-length": 92
}
Body: {"name":"factory_bot","options":["create","calc",{"user_id":1,"title":"Another test calc"}]}

-----------------------------------------------------------

The response we got was:

Status: 500 - Server Error
Headers: {
  "content-length": "7640"
}
Body: Puma caught this error: undefined method `shift' for "create":String (NoMethodError)
(eval):2:in `block in load'
(eval):1:in `map'
(eval):1:in `load'
/Users/george.norris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cypress-on-rails-1.6.0/lib/cypress_on_rails/command_executor.rb:9:in `eval'
/Users/george.norris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cypress-on-rails-1.6.0/lib/cypress_on_rails/command_executor.rb:9:in `load'
/Users/george.norris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cypress-on-rails-1.6.0/lib/cypress_on_rails/middleware.rb:59:in `block in handle_command'
/Users/george.norris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cypress-on-rails-1.6.0/lib/cypress_on_rails/middleware.rb:59:in `map'
/Users/george.norris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cypress-on-rails-1.6.0/lib/cypress_on_rails/middleware.rb:59:in `handle_command'
/Users/george.norris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cypress-on-rails-1.6.0/lib/cypress_on_rails/middleware.rb:18:in `block in call'
/Users/george.norris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cypress-on-rails-1.6.0/lib/cypress_on_rails/configuration.rb:23:in `block in tagged_logged'
/Users/george.norris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/Users/george.norris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/tagged_logging.rb:28:in `tagged'
/Users/george.norris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.2.2/lib/active_support/tagged_logging.rb:80:in `tagged'
/Users/george.norris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cypress-on-rails-1.6.0/lib/cypress_on_rails/configuration.rb:23:in `tagged_logged'
/Users/george.norris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/cypress-on-rails-1.6.0/lib/cypress_on_rails/middleware.rb:18:in `call'
/Users/george.norris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/warden-1.2.8/...


Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `As a logged in user`
    at cypressErr (http://localhost:5000/__cypress/runner/cypress_runner.js:146259:16)
    at cypressErrByPath (http://localhost:5000/__cypress/runner/cypress_runner.js:146268:10)
    at Object.throwErrByPath (http://localhost:5000/__cypress/runner/cypress_runner.js:146231:11)
    at http://localhost:5000/__cypress/runner/cypress_runner.js:135435:21
From previous event:
    at Context.request (http://localhost:5000/__cypress/runner/cypress_runner.js:135431:84)
    at http://localhost:5000/__cypress/runner/cypress_runner.js:144040:33
From previous event:
    at runCommand (http://localhost:5000/__cypress/runner/cypress_runner.js:144019:14)
    at next (http://localhost:5000/__cypress/runner/cypress_runner.js:144162:14)
    at http://localhost:5000/__cypress/runner/cypress_runner.js:144190:16
From previous event:
    at next (http://localhost:5000/__cypress/runner/cypress_runner.js:144162:34)
From previous event:
    at http://localhost:5000/__cypress/runner/cypress_runner.js:144203:37
From previous event:
    at run (http://localhost:5000/__cypress/runner/cypress_runner.js:144196:19)
    at Object.cy.<computed> [as app] (http://localhost:5000/__cypress/runner/cypress_runner.js:144608:11)
    at Context.runnable.fn (http://localhost:5000/__cypress/runner/cypress_runner.js:144840:24)
    at callFn (http://localhost:5000/__cypress/runner/cypress_runner.js:88160:21)
    at Hook.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (http://localhost:5000/__cypress/runner/cypress_runner.js:88147:7)
    at http://localhost:5000/__cypress/runner/cypress_runner.js:148845:28
From previous event:
    at Object.onRunnableRun (http://localhost:5000/__cypress/runner/cypress_runner.js:148833:20)
    at $Cypress.action (http://localhost:5000/__cypress/runner/cypress_runner.js:141111:61)
    at Hook.Runnable.run (http://localhost:5000/__cypress/runner/cypress_runner.js:147641:13)
    at next (http://localhost:5000/__cypress/runner/cypress_runner.js:88662:10)
    at http://localhost:5000/__cypress/runner/cypress_runner.js:88706:5
    at timeslice (http://localhost:5000/__cypress/runner/cypress_runner.js:82632:27)
```

POST
```
FactoryBot.define do
  factory :post do
    title { Faker::Lorem.sentence }
    body { "#{Faker::Number.number(digits: 10)} + #{Faker::Number.number(digits: 10)}" }
    user
  end
end

```

USER

```
FactoryBot.define do
  factory :user do
    sequence :email do |n|
      "#{Faker::Lorem.word}@example.com"
    end

    sequence :password do |n|
      "password-#{Faker::Lorem.word}"
    end

    sequence :username do |n|
      "@user#{Faker::Lorem.word}"
    end

    before(:create) do |user|
      user.skip_confirmation!
    end
  end
end

```

**Comment by grantspeelman** [comment]
You have to change:

```javascript
        cy.appFactories(['create', 'post', attrs])
```

to

```javascript
        cy.appFactories([['create', 'post', attrs]])
```
